### ISSUE TITLE
Class Icon backgrounds sometimes aren’t using the correct theme color.

### ISSUE THREAD

**Issue by DionBlox1** [MaximumADHD/Roblox-Studio-Mod-Manager#102]
I was on dark mode but then the ions went white. @MaximumADHD #102

**Comment by MaximumADHD** [comment]
What does this mean? Are you talking about the class icon editor?

**Comment by DionBlox1** [comment]
Yes. And the studio

**Comment by MaximumADHD** [comment]
Has nothing to do with the mod manager, I can assure you.

**Comment by DionBlox1** [comment]
I will show proof
![20211120_093145](https://user-images.githubusercontent.com/90649001/142721508-2c6fd21b-419f-4514-8991-0a7c8c37b047.jpg)




> Has nothing to do with the mod manager, I can assure you.

**Comment by DionBlox1** [comment]
![blank](https://user-images.githubusercontent.com/90649001/142737843-39feabd5-bedd-48de-afb8-8b31811b78f1.png)

**Comment by DionBlox1** [comment]
Here's a test tube while I wait.
![test-tube_1f9ea](https://user-images.githubusercontent.com/90649001/142738482-6d31bb52-7c6a-43e9-90f0-e685c8fda2bc.png)

**Comment by DionBlox1** [comment]
I ran out of big test tubes so here's a small one.
🧪

**Comment by DionBlox1** [comment]
**It has been 1 day.**  How long will it take?

**Comment by MaximumADHD** [comment]
As far as the issue happening for you in studio itself, that has nothing to do with the mod manager, please double check your studio settings.

This issue is pretty minor and low priority all things considered, but I wanna do a bigger patch to fix some issue with the class icon editor. I’m just taking it easy this weekend since I had to deal with a lot of college homework recently,

**Comment by DionBlox1** [comment]
Its fine

![eXP](https://user-images.githubusercontent.com/90649001/142777670-9dd138f4-79eb-4f13-aa32-9a0abbf5fa21.PNG)







[](url)

**Comment by MaximumADHD** [comment]
Yeah looks like your theme is set to dark. If you would prefer it to be light then change the Theme setting.

**Comment by DionBlox1** [comment]
I like it dark

**Comment by DionBlox1** [comment]
Icon 0 was affected

![iconsssss](https://user-images.githubusercontent.com/90649001/142778657-19ef56ac-68d3-4e31-9ce5-f83ec1c9d0f7.PNG)

**Comment by MaximumADHD** [comment]
Okay cool I get it and all but is this really blocking you from doing anything?
Out of curiosity, can you work around the issue by pressing the theme button again twice?

**Comment by DionBlox1** [comment]
Still broken


https://user-images.githubusercontent.com/90649001/142779014-eaa8c6b3-5c74-46b5-8646-6eb6d309796d.mp4

**Comment by DionBlox1** [comment]
Heres what it looks in studio

![sutdio](https://user-images.githubusercontent.com/90649001/142779049-1a52b429-c184-4203-9d9b-17b026f0f8f3.PNG)

**Comment by MaximumADHD** [comment]
Bizarre, haven’t seen that before. Just wish you had shown that in the first place because I couldn’t tell what you were talking about.

**Comment by DionBlox1** [comment]
Yea.

**Comment by DionBlox1** [comment]
Ive updated it and it still accrued

**Comment by DionBlox1** [comment]
Heres the placeholder, part and model icons

![explorer-icon-2](https://user-images.githubusercontent.com/90649001/143073477-9350ad0b-881d-444d-a3a2-9b77bc830cc4.png)
![explorer-icon-0](https://user-images.githubusercontent.com/90649001/143073479-4d45ae14-316f-4ca1-b412-fe3442b102d3.png)
![explorer-icon-1](https://user-images.githubusercontent.com/90649001/143073480-319157a6-ba38-4076-8dfb-f363089a6208.png)

**Comment by MaximumADHD** [comment]
That isn’t helpful. Though I have reason to suspect this was Roblox’s fault now and not mine. 

Here’s a few things I’d like you to try:
1. Launch Studio with the Force Reinstall checkbox checked, then check and see if the images are still using the white background. Make sure you reset the ones that you’ve modified there or they’ll still have the white background probably.
2. If that doesn’t work, download ![this image](https://raw.githubusercontent.com/MaximumADHD/Roblox-Client-Tracker/roblox/textures/ClassImages.PNG) and save it as `__classImageRef.png` in your `ExplorerIcons` folder. It might say there’s already a file named as that, and if that’s the case you’ll have to [enable showing hidden files](https://support.microsoft.com/en-us/windows/show-hidden-files-0320fe58-0117-fd59-6851-9b7f9840fdb2) to delete the existing one. Again make sure you’ve reset any icons that you’ve overridden or they may still have a white background.

This should fix the issue for now. If it returns though, please let me know.

**Comment by DionBlox1** [comment]
Re instaling
![reinst](https://user-images.githubusercontent.com/90649001/143075849-a0314e4d-7d6d-40db-94a6-5c24f1daa60a.PNG)

**Comment by DionBlox1** [comment]
step 1 fail to step 2 then 
![fail1](https://user-images.githubusercontent.com/90649001/143076817-2564e68a-8b0d-493f-bd51-45121890d04c.PNG)

**Comment by MaximumADHD** [comment]
Can confirm this was Roblox’s fault now, not mine. It was a small slip-up when they added the PathfindingModifier class icon.

https://github.com/MaximumADHD/Roblox-Client-Tracker/blob/26762304120ce6883232e15b48e9ac356fc33e50/textures/ClassImages.PNG

This should be fixed on their end shortly. It’s one of the risks you have to be prepared for if you’re using sitetest2.robloxlabs

In short this had nothing to do with me and Roblox legitimately messed this up on their end with the sitetest2 build lol.

**Comment by DionBlox1** [comment]
Step 2 fixed!

![fix2](https://user-images.githubusercontent.com/90649001/143079647-0594a087-4d2e-4d77-813a-cf52cb06fbb5.PNG)
