### ISSUE TITLE
Has nothing to do with the mod manager, I can assure you. Lies

### ISSUE THREAD

**Issue by DionBlox1** [MaximumADHD/Roblox-Studio-Mod-Manager#103]
I will show proof
![20211120_093145](https://user-images.githubusercontent.com/90649001/142721508-2c6fd21b-419f-4514-8991-0a7c8c37b047.jpg)

Original post: Has nothing to do with the mod manager, I can assure you.

_Originally posted by @MaximumADHD in https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/issues/102#issuecomment-974621052_

**Comment by MaximumADHD** [comment]
Ok cool I’ll fix it. Please don’t spam my email by closing and reopening issues.
