### ISSUE TITLE
./ QtResource patch does not work in Mod Manager Studio

### ISSUE THREAD

**Issue by ghost** [MaximumADHD/Roblox-Studio-Mod-Manager#104]
With the discovery of the ``:/ -> ./`` patch, I've tried to do it with Studio installed with ModManager, however, it doesn't work.

~~Looking at hex comparisons between Roblox's vanilla installer and this version of Studio, there are multiple bytes that are different, including the signature, however I dont believe that changes anything as this is just a distribution issue~~

**UPDATE:** This is directly related to Mod Manager's bootstrapper launching Studio. Launching ``RobloxStudioBeta.exe`` will allow the patches to take effect

**Comment by metatablecat** [comment]
UPDATE: This issue is directly correlated to Mod Manager launching Studio.
Launching Studio from the exe itself will apply the paches
