### ISSUE TITLE
Fix Luau-Powered Autocomplete Documentation when using Mod Manager 

### ISSUE THREAD

**Issue by ACKREIK** [MaximumADHD/Roblox-Studio-Mod-Manager#105]
Currently launching studio via the Mod Manager leaves the Luau-Powered Autocomplete and the documentation broken, with the error

(Looking at game:GetService("Chat"):WaitForChild() documentation)

API Documentation isn't installed properly. Please check the build log to see the error message. (https://ibb.co/rcTjsV1)
What should have been shown, https://ibb.co/dJq2mHH

And although this may just be an issue with me (it works fine when launching normal studio), I'm pretty sure it's just the Mod Manager.

**Comment by MaximumADHD** [comment]
Will investigate tomorrow.

**Comment by MaximumADHD** [comment]
Should be good now.

**Comment by ACKREIK** [comment]
It still seems to be happening.
If it should be good then
