### ISSUE TITLE
Windows 11 👀 

### ISSUE THREAD

**Issue by ZayerRBLX** [MaximumADHD/Roblox-Studio-Mod-Manager#108]
Hi, the application is not yet available for windows 11?

**Comment by Xanderplayz17** [comment]
The exe is compatible from windows 8 all the way to windows 11.

**Comment by LoganDark** [comment]
Windows 11 is Windows, so the application will work on it...

**Comment by aaron819chen** [comment]
it works on my windows 11 pc

**Comment by ZayerRBLX** [comment]
An earlier version however works.

**Comment by ExperiencersInternational** [comment]
@ZayerRBLX try running it in compatibility mode. Right click the executable > Properties > Compatibility > Run in compatibility mode > Choose 'Windows 10'

**Comment by Xanderplayz16** [comment]
> <img alt="image" width="607" src="https://user-images.githubusercontent.com/86352017/154557271-92e00486-b93b-4a70-a598-ce1f43fc663c.png">
> 
> Sorry it's in French but this message appears when I run the .exe

Weird. Seems like a corrupt executable.
