### ISSUE TITLE
Everything is offset

### ISSUE THREAD

**Issue by noahrepublic** [MaximumADHD/Roblox-Studio-Mod-Manager#111]
Whenever I create a text label it is slightly above where it should be in studio, in-game is fine and when I uninstall, same thing with all the names in the models tab and plugins

**Comment by MaximumADHD** [comment]
Does this issue specifically apply to the mod manager though?

**Comment by noahrepublic** [comment]
It seems to be. I had no mods enabled and studio did that until I uninstalled. Don't know if you can fix it though.

**Comment by LoganDark** [comment]
@MaximumADHD Yes this applies specifically to the mod manager. I am experiencing this issue as well. It seems to be a bug with how RSMM installs Studio since it happens even if I launch it directly from `%localappdata%\Roblox Studio`. API Documentation also doesn't work.

**Comment by Elttob** [comment]
I believe I've started getting this issue too, after doing a fresh reinstall of Mod Manager. 

Here's what I see whenever I boot in using Mod Manager - as far as I can tell, this only applies to anything using Source Sans inside a PluginGui, ScreenGui or similar;

![image](https://user-images.githubusercontent.com/11815374/155199054-613a3a3a-f2fe-436a-8133-902fa0fdfd79.png)

This looks like Studio can't find the files it needs to render Source Sans.

**Comment by LoganDark** [comment]
@Elttob Are you experiencing the API documentation issue as well?

**Comment by Elttob** [comment]
This one?
![image](https://user-images.githubusercontent.com/11815374/155200071-be4fef11-ae94-4daf-bfec-068e3b047e84.png)

**Comment by LoganDark** [comment]
> This one? ![image](https://user-images.githubusercontent.com/11815374/155200071-be4fef11-ae94-4daf-bfec-068e3b047e84.png)

Yep, exactly.

**Comment by metatablecat** [comment]
I mentioned this in issue #104 but it appears that the QtResource patch isn't the only thing the custom bootstrapper is messing with.

**Comment by LoganDark** [comment]
I'm not sure what RSMM is doing but it really shouldn't be sabotaging Studio like this when you don't even have any mods installed. I'd say this seems like a huge bug.

**Comment by Elttob** [comment]
This is severely affecting my workflow now. Is there anyone working on this at all?

I don't mind waiting for a fix, and I don't mind if people are busy, but I'm pretty disappointed that a major issue like this has not received a response in the 26 days it has been open for,

**Comment by LoganDark** [comment]
@Elttob Just curious, what prevents you from using the official bootstrapper until this is resolved?

**Comment by Elttob** [comment]
Not so much about myself - it's about people who use my creations that depend on Mod Manager. I've been getting inundated with DMs and bug reports for Vanilla that are basically exactly this problem description, for which I have had to redirect them to Max instead because I don't know how to fix this and it's not within my project scope.

**Comment by ExperiencersInternational** [comment]
Only just realised this is a mod manager issue, it's kinda annoying ngl, I only use Mod Manager for @Elttob's vanilla.

Has anyone tried pasting the Source Sans font (when launching Studio from Mod Manager)into [RobloxStudioFolder]\content\fonts?

**Comment by metatablecat** [comment]
This sounds like a hashing issue with the virtual registry. One of my friends noticed fonts weren't getting installed from the launcher.

I run an older build and dont get this issue.

**Comment by Standit0** [comment]
has clone or the community fixed this yet? this is really annoying

**Comment by MaximumADHD** [comment]
I apologize for neglecting this, I just haven’t personally seen the problem and have been super busy with college and work. I definitely need to setup some kind of unit testing to make sure everything is working as intended.

**Comment by metatablecat** [comment]
The issue here is the font files for SourceSans aren't being placed into `/content/fonts` and instead are placed into the root install directory.

I guess a temporary fix is to drag the files back into the fonts folder?

**Comment by MaximumADHD** [comment]
Looks like it's solved now. You may need to force a reinstallation, but if you see any *.ttf files in Roblox Studio's root directory, just move them into a new folder called StudioFonts and that should fix it.

Patch: https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/commit/eed5f2db4c0547abcb4f38e9d055acd06bd990d7
Release: https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/releases/tag/v2022.4.20
