### ISSUE TITLE
Cannot even download mod manager

### ISSUE THREAD

**Issue by ExperiencersInternational** [MaximumADHD/Roblox-Studio-Mod-Manager#115]
Hi there, I just would like to open an issue (similar to #54), where I cannot even download mod manager.

I will be bypassing Microsoft blocking this by turning SmartScreen off temporarily, but honestly, we should really be given a choice to download it if we want:

![image](https://user-images.githubusercontent.com/56035537/154862405-d186d46a-98ff-46a3-a7a7-8d6c54baf70a.png)

![image](https://user-images.githubusercontent.com/56035537/154862416-6b7ae9b1-bf48-426f-a4fb-8f7798c417fd.png)

Pressing keep anyways does not keep it:

![image](https://user-images.githubusercontent.com/56035537/154862429-4c4f6bbb-a4ed-4652-bd55-a709d0cf1d8d.png)

**Comment by FlynnFarrow** [comment]
Thought turning Smartscreen off temporarily would work around it, but it still won't allow me, I think you would have to download it through Windows Terminal (somehow) for now.

**Comment by ExperiencersInternational** [comment]
Not the best solution, but this should work for now (run in PowerShell)

$source = 'https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/raw/main/RobloxStudioModManager.exe'
$destination = '[use valid folder path here]'
Invoke-WebRequest -Uri $source -OutFile $destination

**Comment by celeranis** [comment]
I'd consider this behavior a Microsoft Edge issue, and the detection itself has always been a pain.

I believe this is the result of Microsoft adding their own SmartScreen antivirus without disabling the one built into Chromium. 

Try going to [edge://downloads](edge://downloads), there may be a _second_ "Allow anyway" option there.

**Comment by ExperiencersInternational** [comment]
@celeranis hi there! I tried doing that and there's no second allow anyway option, instead there is just a retry button (which doesn't help at all)

![image](https://user-images.githubusercontent.com/56035537/156918796-88506b8f-c69e-451a-acd6-e680fda3a999.png)
