### ISSUE TITLE
Malwarebytes Detection

### ISSUE THREAD

**Issue by jwisham** [MaximumADHD/Roblox-Studio-Mod-Manager#117]
![image](https://user-images.githubusercontent.com/24721341/156116830-e3df12e4-2f01-427b-9bce-3551266145f0.png)
Not sure what can be done about this besides just reporting this as a false-positive to malwarebytes.
Feel free to close instantly if I'm stupid for making an issue report for this at 12:30 AM at night.

**Comment by metatablecat** [comment]
See #54
