### ISSUE TITLE
issues installing plugins

### ISSUE THREAD

**Issue by aaron819chen** [MaximumADHD/Roblox-Studio-Mod-Manager#119]
I don't know why but Roblox Studio Mod Manager makes it so when the Roblox site tries to open studio it will open mod manager instead so I can't install plugins.

**Comment by MaximumADHD** [comment]
Launching through the mod manager from the website *should* install the plugin correctly. If it isn’t then let me know.

**Comment by MaximumADHD** [comment]
Closing since I haven’t heard back.
