### ISSUE TITLE
"API Documentation isn't installed properly." message

### ISSUE THREAD

**Issue by spectraljake** [MaximumADHD/Roblox-Studio-Mod-Manager#120]
![image](https://user-images.githubusercontent.com/11815374/155200071-be4fef11-ae94-4daf-bfec-068e3b047e84.png)

_Originally posted by @Elttob in https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/issues/111#issuecomment-1048113305_

Was able to reproduce this and found that Eltobb mentioned it first.
![image](https://user-images.githubusercontent.com/24721341/158092060-17dd78df-8070-4dff-93f1-040f6a7fda9c.png)

**Comment by ACKREIK** [comment]
first check if this folder exists:
C:\Users\username\AppData\Local\Roblox Studio\content\api-docs
and if it does make sure it has a bunch of files in it
if it doesnt then hit force reinstallation and wait
if that doesnt work manually uninstall it, then install default roblox, copy the api docs to a safe location, ininstall it, install studio via mod manager and if the folder isnt there then paste the api docs in

**Comment by MaximumADHD** [comment]
Late response but I believe this issue is resolved now.
If you're on the latest version and still see this issue, let me know!
