### ISSUE TITLE
Scaling issues with plugins / windows.

### ISSUE THREAD

**Issue by catswimmer** [MaximumADHD/Roblox-Studio-Mod-Manager#121]
Hi! I ran into issue where I have scaling issues.
Do someone knows a fix for this? If so, please tell me how to fix that.

![obraz](https://user-images.githubusercontent.com/99511627/163606325-34dc2227-4e03-4651-a7d3-5c9fc4a23cab.png)

**Comment by jwisham** [comment]
Still on-going
![image](https://user-images.githubusercontent.com/24721341/164312430-693356b9-35fb-45ff-a0d6-8701fb1b38ad.png)

**Comment by MaximumADHD** [comment]
Try doing a force reinstall? @jwisham

**Comment by MaximumADHD** [comment]
This issue should be resolved now. Fetch the latest version and if you still see problems, try what I suggested in the original issue report: https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/issues/111#issuecomment-1104253021

**Comment by jwisham** [comment]
> Try doing a force reinstall? @jwisham

Resolved.
