### ISSUE TITLE
Can't find path "...\ExplorerIcons\__classImageRef.png" on latest build.

### ISSUE THREAD

**Issue by antcar0929** [MaximumADHD/Roblox-Studio-Mod-Manager#123]
Hi, I'm trying to force reinstall studio but this poped up.

![unknown](https://user-images.githubusercontent.com/58066418/164984273-791bf8e9-1dde-4fa0-863c-9e5f82ecb3a6.png)

But the folder "ExplorerIcons" dosen't exist. 

![image](https://user-images.githubusercontent.com/58066418/164984486-ad42f904-24f3-4c2a-890b-a4eaed47c84e.png)

I'm using the latest build.

**Comment by antcar0929** [comment]
Seems adding the folder `ExplorerIcons` fixed the issue.

**Comment by MaximumADHD** [comment]
Should be patched with this commit.
https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/commit/9447bdbf6222911234af2bbfbd88960ea6fd8e1f
