### ISSUE TITLE
Roblox studio crashing on load.

### ISSUE THREAD

**Issue by DionBlox1** [MaximumADHD/Roblox-Studio-Mod-Manager#124]
Hi  @MaximumADHD  when I try to load roblox studio this pops up. 
![20220508_124058](https://user-images.githubusercontent.com/90649001/167294874-1a72e009-ba4f-408f-ab44-7eff0461911b.jpg)

Video: it no work

**Comment by MaximumADHD** [comment]
Latest release of the program shouldn't have this issue.

**Comment by DionBlox1** [comment]
Fixed now!
![20220512_203326](https://user-images.githubusercontent.com/90649001/168154769-3578e694-8b7e-46f3-83fb-0d39eb18be29.jpg)
![20220512_203523](https://user-images.githubusercontent.com/90649001/168154783-b175b97c-5730-4505-bb1f-cab821748e00.jpg)
