### ISSUE TITLE
"Roblox Studio is out of date!" message while trying to edit class icons

### ISSUE THREAD

**Issue by purplux** [MaximumADHD/Roblox-Studio-Mod-Manager#126]
![image](https://user-images.githubusercontent.com/69032098/170065066-35bac584-313d-483f-9655-a18cf737177d.png)
I had just updated Studio this morning, so this is odd. I then clicked Yes, but however it took way too long, longer than a normal re-install or an update. I closed the updater and went back to the main menu.
![image](https://user-images.githubusercontent.com/69032098/170065246-1f7ee7ad-6b32-4516-9a58-b38f00c08863.png)
This time, instead of clicking 'Yes" on the update menu, I clicked "No", then it popped up with the interface and error'd me.
![image](https://user-images.githubusercontent.com/69032098/170065752-a60d64db-9587-44e6-ac93-cf94e18193e7.png)
I clicked continue, and the interface was in an initializing loop, and I had to open task manager just to open it.

https://pastebin.com/ek7FiTSB - error logs

**Comment by MaximumADHD** [comment]
Will investigate.

**Comment by MaximumADHD** [comment]
Should be patched with this commit.
https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/commit/9447bdbf6222911234af2bbfbd88960ea6fd8e1f
