### ISSUE TITLE
Any way to quickly set all icons to override?

### ISSUE THREAD

**Issue by Kingminer7** [MaximumADHD/Roblox-Studio-Mod-Manager#128]
Is there any way to have all icons be overridden? Somehow all icons are no longer overridden, and I want to know if there is an easier way.

**Comment by MaximumADHD** [comment]
Copying and pasting them into the ExplorerIcons folder should automatically do that for you.

**Comment by Kingminer7** [comment]
At one point, they randomly unchecked, and even after deleting and repasting, they did not override automatically.

**Comment by MaximumADHD** [comment]
Closing this for now as I’ve sunset the class icon editor.
