### ISSUE TITLE
Latest Release does not run

### ISSUE THREAD

**Issue by HooferDevelops** [MaximumADHD/Roblox-Studio-Mod-Manager#130]
I decided to update my mod manager as I had not in a long time, to realize that the executable would not run. While trying to debug the problem, I discovered that it would have a background task appearing in task manager. However, after killing those tasks, I could not get them to re-appear, with the application not doing anything when running.

The release prior to the latest release runs with no issues. The executable that is in the [commits](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/blob/main/RobloxStudioModManager.exe) does not run as well. I am on the latest security update for Windows 11, I have no anti-virus as well. Apologies that I can not provide any more information, it is really hard to obtain any information when it does not give me any sort of errors or possible reasoning as to why this would occur.

**Comment by metatablecat** [comment]
This happens on Windows 10 as well, a short workaround is to launch Studio directly from `/AppData/Local/Roblox Studio/RobloxStudioBeta.exe`

**Comment by HooferDevelops** [comment]
After performing a full operating system factory reset, I was able to run the latest release. I am not sure why that solved the issue, or why the issue persisted in the first place.
