### ISSUE TITLE
Meshes not showing in normal studio/actual game

### ISSUE THREAD

**Issue by UnearthlyGoose** [MaximumADHD/Roblox-Studio-Mod-Manager#131]
So, i imported portal 2 models using source2roblox but meshes isnt showing in actual game or normal studio
Works only in Roblox Studio Mod Manager
Can i fix it?
![Screenshot 2022-07-26 025457](https://user-images.githubusercontent.com/96787750/181007609-8a98f62f-2dc2-402f-8142-023603418747.png)
![Screenshot 2022-07-26 025127](https://user-images.githubusercontent.com/96787750/181007619-9e29b3c2-570e-4a9c-bba6-39d6ff88e094.png)

**Comment by MaximumADHD** [comment]
Wrong repository. Use the -upload command line option.

**Comment by kolyapichkur** [comment]
> Wrong repository. Use the -upload command line option.

Uh, there is no "issues" tab in the source2roblox repository.
