### ISSUE TITLE
Repeating Roblox Studio Crashes

### ISSUE THREAD

**Issue by 6ixfalls** [MaximumADHD/Roblox-Studio-Mod-Manager#132]
Looks like an issue with the latest Roblox Studio update, about 90% of the time I get the error "Studio.App.RobloxApplication.AbnormalTerminateMessage" 
![image](https://user-images.githubusercontent.com/23470032/183014634-19545c9c-b117-40e8-b3f1-ab063e1b253b.png)
Roblox Studio logs don't have anything noteworthy, seems to just cut off. Latest version of Roblox Studio & Roblox Studio Mod Manager.

**Comment by HexaRG** [comment]
same here
![image](https://user-images.githubusercontent.com/67880600/183232478-0a6f87a0-17ea-4a41-bce4-600ab710a17e.png)

**Comment by 6ixfalls** [comment]
Found some more information on this issue, according to @aNewMoose on the DevForum, Roblox Studio Mod Manager isn't installing an important file, causing Roblox Studio to crash.
https://devforum.roblox.com/t//1908337/6

**Comment by MaximumADHD** [comment]
Are you guys on the latest version of the bootstrapper?
I patched this recently.

**Comment by 6ixfalls** [comment]
Latest version does seem to have fixed it, thanks.
