### ISSUE TITLE
Studio not working

### ISSUE THREAD

**Issue by DionBlox1** [MaximumADHD/Roblox-Studio-Mod-Manager#133]
I got this message
![Screenshot (3)](https://user-images.githubusercontent.com/90649001/184347638-1360aa02-e531-4a02-838a-fc8be408f8f0.png)
@MaximumADHD please fix it

**Comment by MacaylaMarvelous81** [comment]
I encountered the same issue, but it's working again now... probably something else

**Comment by Rawblocky** [comment]
Same thing happens to me, it happens like 95% of the time. Force Reinstallation fixes it, however, it only fixes it for only that session. I had to move back to Roblox's original Roblox Studio for the time being which sucks.

**Comment by MaximumADHD** [comment]
Make sure you have the latest mod manager version installed. This has been patched.

**Comment by DionBlox1** [comment]
It works now thank you

**Comment by DionBlox1** [comment]
Necvermind it broke again

**Comment by MaximumADHD** [comment]
Try forcing a reinstall @DionBlox1?

**Comment by DionBlox1** [comment]
Still no work

**Comment by MacaylaMarvelous81** [comment]
I encountered this on eed5f2d and b09aca1

**Comment by MaximumADHD** [comment]
Can you guys elaborate on what's happening?
Is it throwing an exception, is it just never starting? 
I need more information to see if I can reproduce it on my end.
