### ISSUE TITLE
Certain windows are completely blank

### ISSUE THREAD

**Issue by SomewhatMay** [MaximumADHD/Roblox-Studio-Mod-Manager#135]
Some windows (as shown below) are completely blank and on others, text is missing. The two notable ones are the Game Settings window and the game Publish window (including when you press update existing game).

Here are the images:
![image](https://user-images.githubusercontent.com/40745122/185770059-c03e6eb0-bc1b-4047-bd34-c7595936ff78.png)
![image](https://user-images.githubusercontent.com/40745122/185770063-5c143451-1358-45c8-b3a2-f6fbbd7d3459.png)
![image](https://user-images.githubusercontent.com/40745122/185770072-70ddf647-f818-4bfc-8bda-64509a4c064c.png)
![image](https://user-images.githubusercontent.com/40745122/185770081-8f53290c-3282-42ef-9dcd-346d9684e580.png)
![image](https://user-images.githubusercontent.com/40745122/185770086-dd3bbc0c-1c14-4a6a-a3d0-62cf09bedb24.png)

I am running the latest version currently with custom Icons enabled.

**Comment by MaximumADHD** [comment]
Check the instructions on the latest release, this issue should be fixed now:
https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/releases/tag/v2022.08.24
