### ISSUE TITLE
Attempting to load game via Edit button on website results in an infinite loading loop

### ISSUE THREAD

**Issue by FutureCiderr** [MaximumADHD/Roblox-Studio-Mod-Manager#141]
As the title says attempting to edit a game via the website results in a "Loading place" loop despite having a good connection and the place being the default roblox baseplate template.

**Comment by MaximumADHD** [comment]
I can’t seem to reproduce this. Is the program just hanging?

**Comment by FutureCiderr** [comment]
Ended up finding a fix by playing around in regedit(deleted RSMM and re-ran the program). Although finding a new issue by doing that is that opening places or attempting to install plugins(practically anything that launches studio from the browser) results in an Access denied(key elevation policy) error. Unsure if this is related to RSMM or if its just me /shrug

**Comment by MaximumADHD** [comment]
Okay, you're definitely on a really old version of the program.
I'd recommend switching to the latest release.
