### ISSUE TITLE
macOS?

### ISSUE THREAD

**Issue by Adamfal** [MaximumADHD/Roblox-Studio-Mod-Manager#150]
Hi

Is this available on macOS, or is it just windows?

**Comment by MaximumADHD** [comment]
Only Windows, and this is not changing right now.

**Comment by Adamfal** [comment]
You seem a bit irritated about this. I made the same post yesterday, and you closed it without reason, and now you somehow decide to respond and then close.

A bit unprofessional of you.

**Comment by randomizednum** [comment]
> You seem a bit irritated about this. I made the same post yesterday, and you closed it without reason, and now you somehow decide to respond and then close.
> 
> A bit unprofessional of you.
> 

It makes sense to close the issue because it is a duplicate of [another issue](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/issues/24). Besides, this is a duplicate of your previous issue. He gave a clear "no (for now)" response after closing (I don't think you've seen that).
