### ISSUE TITLE
Issues with channels

### ISSUE THREAD

**Issue by EasternBloxxer** [MaximumADHD/Roblox-Studio-Mod-Manager#157]
![image](https://user-images.githubusercontent.com/54174182/218992696-40fef14e-7b01-4a07-894f-e79ac8d1713c.png)
![image](https://user-images.githubusercontent.com/54174182/218992732-5f26a9df-68dc-41c8-af93-87360934200a.png)
Versions are off.... just a bit.....
latest is Studio64 version-hidden at 2/13/2023 4:13:17 PM, file version: 0, 563, 0, 5630392, git hash: 
So using a channel will just install some ancient version you cant use

**Comment by MaximumADHD** [comment]
Roblox cut off versioning history in channels outside of production when they did the `version-hidden` change to their `DeployHistory.txt` log files. The latest build disables selecting versions when you aren’t using the LIVE channel. This is unfortunately expected behavior.

**Comment by EasternBloxxer** [comment]
Yeah but even when i selected latest i had some ancient clients. When i built from source those issues didnt occur maybe i just messed something up before without realizing

**Comment by metatablecat** [comment]
For the time being, if you do really want to use these channels, you can force the Roblox installer to install them by changing the following registry keys (the `(default)` key) to `zcanary` or `zintegration`
`HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxStudio\Channel`
`HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\roblox-studio\Channel`

**Comment by EasternBloxxer** [comment]
> For the time being, if you do really want to use these channels, you can force the Roblox installer to install them by changing the following registry keys (the `(default)` key) to `zcanary` or `zintegration` `HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxStudio\Channel` `HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\roblox-studio\Channel`
> 
> Also have fun changing it back every single time you want to access these channels because Roblox decided to change it back to `production` when you start Studio

I already got a better method of using channels. (launch arguments)

**Comment by EasternBloxxer** [comment]
Also said i fixed the issue with roblox studio mod manager
