### ISSUE TITLE
Installed the latest version of Roblox Studio Mod Manager and channels are now forced to (Use Latest) except for LIVE

### ISSUE THREAD

**Issue by alpharetzy** [MaximumADHD/Roblox-Studio-Mod-Manager#160]
After reinstalling RSMM to update it, i noticed something is not right.

The LIVE channel version selector still works fine, and as intended:

![image](https://user-images.githubusercontent.com/112749084/225608572-0a574550-61ba-4b30-a7e1-008ad23fe34c.png)

Other channels however, such as zCanary, zQtitanStudioReleaseHighDpi have their version selector disabled and forced to (Use Latest). Picture:

![image](https://user-images.githubusercontent.com/112749084/225609124-789f3319-0056-4331-a34f-1aa47e4c486a.png)

But finally, at least for zQtitanStudioReleaseHighDpi, more versions have been supposedly added and now installs the true latest version from this channel, which is 0.549.395.5490662 and this version is supposedly the first version to have the new icons (not the controversial blue ones), but the current icons that for the Instance, it look better. But the ribbon icons are now colorless because they are now white in dark & black in light.

**Comment by alpharetzy** [comment]
> After reinstalling RSMM to update it, i noticed something is not right.
> 
> The LIVE channel version selector still works fine, and as intended:
> 
> ![image](https://user-images.githubusercontent.com/112749084/225608572-0a574550-61ba-4b30-a7e1-008ad23fe34c.png)
> 
> Other channels however, such as zCanary, zQtitanStudioReleaseHighDpi have their version selector disabled and forced to (Use Latest). Picture:
> 
> ![image](https://user-images.githubusercontent.com/112749084/225609124-789f3319-0056-4331-a34f-1aa47e4c486a.png)
> 
> But finally, at least for zQtitanStudioReleaseHighDpi, more versions have been supposedly added and now installs the true latest version from this channel, which is 0.549.395.5490662 and this version is supposedly the first version to have the new icons (not the controversial blue ones), but the current icons that for the Instance, it look better. But the ribbon icons are now colorless because they are now white in dark & black in light.

Is this a bug or is it intentional?

**Comment by alpharetzy** [comment]
Is this a bug or is this intentional?

**Comment by MaximumADHD** [comment]
Intentional because Roblox doesn’t keep public version history logs for builds that aren’t production. All of the version guids are recorded as “version-hidden”

There isn’t anything *necessarily* stopping people from keeping records of this themselves, but I wouldn’t count on those files being around for long. I’m not presently interested in doing this myself.
