### ISSUE TITLE
Adding Roblox-Deploy-History as a submodule (+ some other stuff)

### ISSUE THREAD

**Issue by pizzaboxer** [MaximumADHD/Roblox-Studio-Mod-Manager#163]
I noticed that the project depends on Roblox-Deploy-History, which it assumes to be two folders up from the ProjectSrc folder. If you added Roblox-Deploy-History as a git submodule inside ProjectSrc, then it just makes things a bit easier and clearer to set up.
So, you could instead have it located at `ProjectSrc\RobloxDeployHistory` while still having it linked to the repository. I'm just wondering if that's something you're okay with having.

Also, does the built executable have to be commited to the repository? Seems redundant since you publish them as releases anyway.

**Comment by MaximumADHD** [comment]
I'd do that if it didn't create conflict in RCT-Source (since it isn't being handled as a package atm), and historically putting the built executable into the repository was necessary because I was a lazy asshat and didn't always use releases.
