### ISSUE TITLE
Any help [System Error]

### ISSUE THREAD

**Issue by 5h1b** [MaximumADHD/Roblox-Studio-Mod-Manager#187]
Hi i get this error when i open flag editor
![Screenshot 2023-08-13 160330](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/assets/62843852/68f12c2a-e7c2-4ffb-ba2b-8cad37dbb860)
![Screenshot 2023-08-13 160348](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/assets/62843852/f3c31a2e-6d90-41d3-9fdf-0a991363877e)
![Screenshot 2023-08-13 160319](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/assets/62843852/bea294b1-fe58-4d26-83b5-e9ed5046d31e)
Any help i don't know what to call this rename it when resolved

**Comment by 5h1b** [comment]
:(

**Comment by uiojaafdosijfafdssf** [comment]
Have you tried reinstalling the program? As it says in the errors, it may fix that problem.

**Comment by 5h1b** [comment]
yes didn't fix it

**Comment by 5h1b** [comment]
This issue is 1 year and 2 months old, with no fix found. I have since gotten a new PC which has fix this problem, I am guessing that it was a problem was with my PC as I remember having multiple errors on that PC with different applications.
