### ISSUE TITLE
Breaking Exporting - Dev assets stuff (eg. Toolbox.)

### ISSUE THREAD

**Issue by ZixiousYT** [MaximumADHD/Roblox-Studio-Mod-Manager#189]
Hello, I've been with a **nightmare** today. My Toolbox and popups don't Appear. Why? Look  yourself, It's not a valid file. Please help me, or someone give the toolbox.rbxm.

- [ ] Solve the problem.
![image_2023-09-19_200600670](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/assets/137488516/4d0df8f8-83be-4f9d-83d0-d819a711347a)

**Comment by MaximumADHD** [comment]
Force a reinstall.
