### ISSUE TITLE
Stuck in a logging in loop

### ISSUE THREAD

**Issue by 7B3XR** [MaximumADHD/Roblox-Studio-Mod-Manager#201]
I am using 578 version and it's constantly saying log in failed.
![image](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/assets/100047449/e6ee6c11-1a5e-4200-8d1d-2d0f2498f612)

**Comment by MaximumADHD** [comment]
Old builds of Roblox are likely broken due to protocol changes. Not much I can do unfortunately.
