### ISSUE TITLE
sitetest access does not work.

### ISSUE THREAD

**Issue by metatablecat** [MaximumADHD/Roblox-Studio-Mod-Manager#96]
As with the restoring of sitetest branches, it will not install the new branches from the amazon dumps.

If doing the hack where you remove the registry key from regedit, it'll 403 and refuse to install.

**Comment by MaximumADHD** [comment]
Investigating...

**Comment by MaximumADHD** [comment]
Whoops. Should be fixed now.
https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/commit/52eea784163e2d73c61a2f0aa32baf312e000bdb
